backend:
  name: github
  repo: <MrShrekles>/<Check20>
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

publish_mode: editorial_workflow  # optional drafts

collections:
  - label: "Gods"
    name: "gods"
    files:
      - label: "Gods JSON"
        name: "gods_json"
        file: "data/gods.json"
        format: "json"
        fields:
          - label: "Gods"
            name: "root"
            widget: list
            label_singular: "God"
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Words, name: words, widget: string, hint: "Comma or pipe separated"}
              - {label: Description, name: desc, widget: text}
              - {label: Location, name: location, widget: string}
              - {label: Rank, name: rank, widget: number, value_type: float}
              - {label: Lineage, name: lineage, widget: string}
              - {label: Tag, name: tag, widget: string, hint: "Comma or pipe separated"}
